modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/IAFEnvoy/HappyGhastLegacy/issues"
license = "All Right Reserved"

[[mods]]
modId = "happy_ghast_legacy"
version = "${version}"
displayName = "Happy Ghast Legacy"
authors = "IAFEnvoy"
description = '''
Happy Ghast backport from 25w15a
'''
logoFile = "logo.png"

[[dependencies.happy_ghast_legacy]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.happy_ghast_legacy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.happy_ghast_legacy]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
