modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/IAFEnvoy/HappyGhastLegacy/issues"
license = "All Right Reserved"

[[mods]]
modId = "happy_ghast_legacy"
version = "${version}"
displayName = "Happy Ghast Legacy"
authors = "IAFEnvoy"
description = '''
Happy Ghast backport from 25w15a
'''
logoFile = "logo.png"

[[dependencies.happy_ghast_legacy]]
modId = "neoforge"
type = "required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.happy_ghast_legacy]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.happy_ghast_legacy]]
modId = "architectury"
type = "required"
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "happy_ghast_legacy.mixins.json"